### PR TITLE
Obs coverage

### PR DESCRIPTION
**Pull request by potash**
@beamalsky here's a more comprehensive check of NWS observations. it calculates what I'm calling coverage of thee observations in the given interval, i.e. the maximum gap in the interval (start_time, end_time) that doesn't have an observation.

Sorry I didn't see you already opened a PR related to this. Can you merge this branch `obs-coverage` into your PR?

Also I'm not seeing tests running for this or the other PR. Should I be?

### CODE REVIEW

**Comment by potash** [comment]
Also the check says that this maximum gap is no more than 4 hours. I picked that somewhat arbitrarily. I ran it for San Francisco for the week and it passed. I have no idea if it this is a strict criteria or what.

As I mentioned elsewhere I know that there have been days where the API is delayed-- no new observations coming in for 6-12 hours. Once it was delayed for almost a week. But I think it's only happened 2-3 times in the past year.

**Comment by beamalsky** [comment]
Checking for gaps throughout is a nice technique! I'm curious about how often the 4 hours will get flagged for us, and if it's more than once a week I'd maybe want to increase it to 6, but we can cross that bridge if we get there. 

I've added in my Sentry integration here, which means I get this nice dashboard and should get an email whenever it doesn't pass that 4 hour gap test.

Screen Shot 2020-03-09 at 9 48 00 AM

There can only be one member on a project for the free version of Sentry, but if you're interested in keeping an eye on this too I can share the password. I'm happy to be the point person on these errors. 

Now that I set up Github Actions there should be a green check or red x next to each commit you've pushed. Like this: 

Screen Shot 2020-03-09 at 9 52 20 AM

If you click `Details` it will take you to each step of the Action, and if you look at the details for `Test with pytest` you can see how the tests did/why they failed. You can also do all this from the `Actions` tab by the top of the repo. Let me know if you have any trouble with this!

**Comment by potash** [comment]
Great thanks! 

Though when sentry captures errors locally it does so quietly which hinders debugging. How can I still see the traces locally? We could just print the exception in the same block that gives it to sentry. This raises the more general question of how I should be testing changes locally. Right now what I do is open ipython and do `get_place()` and `write_tweet()` manually. Not the most elegant way. Suggestions?

**Comment by beamalsky** [comment]
We could definitely `print()` something about the error as well as logging it to Sentry! I documented how I test locally in the README: https://github.com/istheweatherweird/itww_bot#running-the-app-locally

Have you tried that? It's a little outdated, I'm now realizing, so I'll updated it in a minute. But this general approach works for me.

**Pull request merged**
